#ifndef SNVM_CONFIG_H
#define SNVM_CONFIG_H

#define SNVM_MPFS_HAL_FIRST_HART  0
#define SNVM_MPFS_HAL_CLEAR_MEMORY  1
#define SNVM_HLS_DEBUG_AREA_SIZE     64
#define NUM_CACHEWAYS_AT_RESET 1
#define SNVM_HLS_MAIN_HART_STARTED               0x12344321U
#define SNVM_HLS_OTHER_HART_IN_WFI               0x12345678U
#define SNVM_HLS_OTHER_HART_PASSED_WFI           0x87654321U
#define SNVM_HLS_MAIN_HART_FIN_INIT              0x55555555U

#define SNVM_MPFS_HAL_FIRST_HART  0

#define INTEGER_CONTEXT_SIZE (32 * REGBYTES)

#define SNVM_SHARED_MEM_INITALISED_MARKER        0xA1A2A3A4UL
#define SNVM_SHARED_MEM_DEFAULT_STATUS           0x00000000UL

#ifndef __ASSEMBLER__

enum SNVM_HSSHartId {
  SNVM_HSS_HART_E51 = 0,
  SNVM_HSS_HART_U54_1,
  SNVM_HSS_HART_U54_2,
  SNVM_HSS_HART_U54_3,
  SNVM_HSS_HART_U54_4,
  SNVM_HSS_HART_ALL
};
#endif

#endif
